param(
    [Parameter(Mandatory=$true)]
    [string]$Version
)

$ErrorActionPreference = "Stop"
$ProjectRoot = Split-Path -Parent $PSScriptRoot
Set-Location $ProjectRoot

# Prüfen ob gh installiert ist
if (!(Get-Command gh -ErrorAction SilentlyContinue)) {
    Write-Error "GitHub CLI (gh) is not installed. Install it from https://cli.github.com/"
    exit 1
}

# Prüfen ob gh authentifiziert ist
gh auth status 2>&1 | Out-Null
if ($LASTEXITCODE -ne 0) {
    Write-Error "Not authenticated with gh. Run 'gh auth login' first."
    exit 1
}

$Tag = "v$Version"

# 1. Version in package.json setzen
$pkg = Get-Content package.json -Raw | ConvertFrom-Json
$pkg.version = $Version
$pkg | ConvertTo-Json -Depth 10 | Set-Content package.json
Write-Output "✔ package.json version set to $Version"

# 2. Commit und Tag
git add package.json scripts/release.ps1 .github/workflows/build.yml
git commit -m "$Tag"
git push origin main
$LASTEXITCODE = 0
git tag -f "$Tag"
git push origin "$Tag" --force
Write-Output "✔ Pushed tag $Tag to crux-client"

# 3. Release auf crux-client erstellen (triggert die GitHub Action)
gh release create "$Tag" --title "$Tag" --notes "Crux Client $Tag" -R "Dev-Reds/crux-client"
Write-Output "✔ Release $Tag created on crux-client (build + upload will run automatically)"

# 4. Lokal crux_code.zip bauen
Write-Output "✔ Building crux_code.zip..."
$zipPath = Join-Path $env:USERPROFILE "Downloads\crux_code.zip"
if (Test-Path $zipPath) { Remove-Item $zipPath -Force }

# Alle Dateien zippen außer node_modules und .git
$compress = @{
    Path = (Get-ChildItem -Path $ProjectRoot -Exclude "node_modules", ".git" | Select-Object -ExpandProperty FullName)
    DestinationPath = $zipPath
    CompressionLevel = "Optimal"
}
Compress-Archive @compress -Force
Write-Output "✔ crux_code.zip created at: $zipPath"

# 5. Zip ins crux-code Release hochladen
Write-Output "✔ Uploading crux_code.zip to crux-code release $Tag..."
gh release upload "$Tag" "$zipPath" --clobber -R "Dev-Reds/crux-code" 2>&1 | Out-Null
if ($LASTEXITCODE -ne 0) {
    gh release create "$Tag" "$zipPath" --title "Crux Code $Tag" --notes "Autogenerated source zip" -R "Dev-Reds/crux-code"
    Write-Output "✔ Release $Tag created on crux-code and zip uploaded"
} else {
    Write-Output "✔ crux_code.zip uploaded to existing release $Tag on crux-code"
}

Write-Output "`nDone!"
Write-Output "  Installer: https://github.com/Dev-Reds/crux-client/releases/tag/$Tag"
Write-Output "  Zip:       https://github.com/Dev-Reds/crux-code/releases/latest/download/crux_code.zip"
